# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0006_auto_20181107_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='message_type_hash',
            field=models.CharField(db_index=True, default='0', max_length=255),
            preserve_default=False,
        ),
    ]
