# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0008_auto_20190325_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logtable',
            unique_together=set([('message_type_hash', 'log_time', 'user_name')]),
        ),
    ]
