# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-03 12:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import openedx.core.djangoapps.xmodule_django.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0010_auto_20190325_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVisitsByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('users_ids', models.TextField(default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('commentable_id', models.CharField(db_index=True, max_length=255)),
                ('discussion_id', models.CharField(max_length=255)),
                ('thread_type', models.CharField(blank=True, max_length=255, null=True)),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionActivityByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='LastCourseVisitByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentStepCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('subsection_id', models.CharField(max_length=255)),
                ('current_unit', models.CharField(max_length=255)),
                ('target_unit', models.CharField(max_length=255)),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoViewsByBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('video_block_id', models.CharField(db_index=True, max_length=255)),
                ('count_full_viewed', models.IntegerField(default=0)),
                ('count_part_viewed', models.IntegerField(default=0)),
                ('video_duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoViewsByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('video_block_id', models.CharField(db_index=True, max_length=255)),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('users_ids', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='VideoViewsByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
                ('video_block_id', models.CharField(db_index=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('viewed_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='lastprocessedlog',
            name='processor',
            field=models.CharField(choices=[(b'EN', b'Enrollment'), (b'VI', b'VideoViews'), (b'DA', b'Discussion activity'), (b'ST', b'Student step'), (b'CA', b'Course activity')], max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='videoviewsbyuser',
            unique_together=set([('course', 'user_id', 'video_block_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoviewsbyday',
            unique_together=set([('course', 'video_block_id', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoviewsbyblock',
            unique_together=set([('course', 'video_block_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='lastcoursevisitbyuser',
            unique_together=set([('user_id', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='discussionactivitybyday',
            unique_together=set([('course', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursevisitsbyday',
            unique_together=set([('course', 'day')]),
        ),
    ]
