# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-01 01:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0012_auto_20181115_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevisitsbyday',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionactivity',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionactivitybyday',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollmentbyday',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lastcoursevisitbyuser',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentstepcourse',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoviewsbyday',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoviewsbyuser',
            name='cohort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursevisitsbyday',
            name='users_ids',
            field=models.TextField(default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='videoviewsbyday',
            name='users_ids',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursevisitsbyday',
            unique_together=set([('course', 'day', 'cohort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='discussionactivitybyday',
            unique_together=set([('course', 'day', 'cohort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentbyday',
            unique_together=set([('course', 'day', 'cohort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='lastcoursevisitbyuser',
            unique_together=set([('user_id', 'course', 'cohort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoviewsbyday',
            unique_together=set([('course', 'video_block_id', 'day', 'cohort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoviewsbyuser',
            unique_together=set([('course', 'user_id', 'video_block_id', 'cohort_id')]),
        ),
    ]
