# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 14:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0012_auto_20181115_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='message_type_hash',
            field=models.CharField(db_index=True, default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursevisitsbyday',
            name='users_ids',
            field=models.TextField(default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='videoviewsbyday',
            name='users_ids',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
