# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 14:50
from __future__ import unicode_literals

from django.db import migrations
import hashlib


def apply_hash(apps, schema_editor):
    LogTable = apps.get_model('rg_instructor_analytics_log_collector', 'LogTable')
    for log_table in LogTable.objects.all():
        try:
            m_hash = hashlib.sha256(log_table.message_type).hexdigest()
        except UnicodeEncodeError:
            m_hash = hashlib.sha256(log_table.message_type.encode('utf-8')).hexdigest()
        log_table.message_type_hash = m_hash
        log_table.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rg_instructor_analytics_log_collector', '0013_auto_20190322_1046'),
    ]

    operations = [
        migrations.RunPython(apply_hash),
    ]
